# Generated by Django 2.1.5 on 2019-03-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceindex',
            name='data_type',
            field=models.PositiveIntegerField(choices=[('int', 'int'), ('str', 'str'), ('float', 'float')], default=int, verbose_name='数据指标类型'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=64, verbose_name='服务名称'),
        ),
    ]
