# Generated by Django 2.1.5 on 2019-03-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20190329_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceindex',
            name='index_name',
            field=models.CharField(max_length=64),
        ),
    ]
